# Generated by Django 6.0.7 on 2026-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('repo_url', models.CharField(max_length=500)),
                ('programming_language', models.CharField(blank=True, max_length=50, null=True)),
                ('external_issue_id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_base', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pr_request', models.BooleanField(default=False)),
                ('code_review_request', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting requirements'), ('planning', 'Planning'), ('cloning', 'Cloning'), ('running', 'Running'), ('verifying', 'Verifying changes'), ('committing', 'Committing'), ('pushing', 'Pushing'), ('opening_pr', 'Opening PR'), ('reporting', 'Reporting'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('callback_url', models.URLField()),
                ('callback_secret', models.CharField(max_length=256)),
                ('pr_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
