# Generated by Django 6.0.7 on 2026-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='callback_url',
            field=models.URLField(max_length=500),
        ),
    ]
