# Generated by Django 6.0.7 on 2026-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_align_task_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='callback_url',
            field=models.URLField(),
        ),
    ]
