# Generated by Django 6.0.7 on 2026-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_fix_callback_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='callback_secret',
            field=models.CharField(max_length=1024),
        ),
    ]
