services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    command: celery -A config worker -Q execute --concurrency=3 -l info -n execute@%h
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
